version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: cicd-webapp-nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webapp-network

  # Redis for future use (session storage, caching)
  redis:
    image: redis:7-alpine
    container_name: cicd-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - webapp-network

volumes:
  redis_data:
    driver: local

networks:
  webapp-network:
    driver: bridge
    name: cicd-network
    